
/**
 * search.js — Client-side search implementation for Chappaqua Poison
 * Auto-generated by build_search_index.py
 */

(function() {
  'use strict';

  const SearchEngine = {
    index: [],

    init: async function() {
      try {
        const response = await fetch('./search_index.json');
        const data = await response.json();
        this.index = data.documents || [];
        this.attachListeners();
      } catch (error) {
        console.error('Failed to load search index:', error);
      }
    },

    search: function(query) {
      if (!query || query.length < 2) return [];

      const q = query.toLowerCase();
      const results = [];

      for (const doc of this.index) {
        let score = 0;

        // Title match (highest weight)
        if (doc.title.toLowerCase().includes(q)) {
          score += 30;
          // Exact title match
          if (doc.title.toLowerCase() === q) {
            score += 20;
          }
        }

        // Phase match
        if (doc.phase.toLowerCase().includes(q) || doc.phase_name.toLowerCase().includes(q)) {
          score += 10;
        }

        // Tags match
        if (doc.tags.toLowerCase().includes(q)) {
          score += 15;
        }

        // Summary match
        if (doc.summary.toLowerCase().includes(q)) {
          score += 5;
        }

        // Date context match
        if (doc.date_context.toLowerCase().includes(q)) {
          score += 10;
        }

        if (score > 0) {
          results.push({
            ...doc,
            score: score
          });
        }
      }

      // Sort by relevance score descending
      results.sort((a, b) => b.score - a.score);

      return results.slice(0, 20);  // Return top 20 results
    },

    attachListeners: function() {
      const searchInput = document.getElementById('search-input');
      const searchResults = document.getElementById('search-results');

      if (!searchInput || !searchResults) return;

      searchInput.addEventListener('input', (e) => {
        const query = e.target.value.trim();

        if (query.length < 2) {
          searchResults.classList.add('hidden');
          return;
        }

        const matches = this.search(query);

        if (matches.length === 0) {
          searchResults.innerHTML = '<div class="search-result-item">No results found</div>';
          searchResults.classList.remove('hidden');
          return;
        }

        searchResults.innerHTML = matches.map(doc => `
          <a href="./posts/$${doc.id}.html" class="search-result-item">
            <div class="search-result-title">${this.escapeHtml(doc.title)}</div>
            <div class="search-result-meta">
              <span class="search-result-phase">${doc.phase_display || ('Act ' + doc.phase)}</span>
              <span class="search-result-date">${this.escapeHtml(doc.date_context)}</span>
            </div>
          </a>
        `).join('');

        searchResults.classList.remove('hidden');
      });

      searchInput.addEventListener('blur', () => {
        setTimeout(() => searchResults.classList.add('hidden'), 200);
      });
    },

    escapeHtml: function(text) {
      const div = document.createElement('div');
      div.textContent = text;
      return div.innerHTML;
    }
  };

  // Initialize on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => SearchEngine.init());
  } else {
    SearchEngine.init();
  }

  // Export for testing
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = SearchEngine;
  }
})();
