#!/usr/bin/env python3
"""
build_search_index.py — Generate Lunr.js-compatible search index

Reads posts.json and generates:
  1. _site/search_index.json — Lunr-compatible document index
  2. _site/js/search.js — Client-side search implementation

Each document includes:
  - id, title, phase, tags (joined), summary, date_context
"""

import json
import os
import sys
from pathlib import Path

def load_posts(posts_file):
    """Load posts from JSON file"""
    with open(posts_file, 'r') as f:
        data = json.load(f)
    return data.get('posts', [])

def load_tokens(tokens_file):
    """Load tokens.json for phase name resolution"""
    with open(tokens_file, 'r') as f:
        return json.load(f)

STANDARD_PHASES = {'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX'}

def resolve_phase_name(post, tokens):
    """Resolve display-ready phase_name from tokens.json (palette.phase)"""
    phase = post.get('phase', '')
    phases = tokens.get('palette', {}).get('phase', {})
    phase_info = phases.get(phase, {})
    return phase_info.get('name', '')

def build_search_documents(posts, tokens):
    """
    Transform posts into search-friendly documents.
    Each document has: id, title, phase, phase_name, tags, summary, date_context
    Phase names are resolved from tokens.json, not stored in posts.json.
    """
    documents = []

    for post in posts:
        post_id = post.get('id', '')
        phase = post.get('phase', '')
        phase_name = resolve_phase_name(post, tokens)

        # For special phases, phase_display is just the name (e.g. "Preface")
        # For standard phases, it's "Act V — The Cover"
        if phase in STANDARD_PHASES:
            phase_display = f"Act {phase} — {phase_name}" if phase_name else f"Act {phase}"
        else:
            phase_display = phase_name or phase

        doc = {
            'id': post_id,
            'number': post.get('number'),
            'title': post.get('title', ''),
            'url': f'./posts/{post_id}.html',
            'phase': phase,
            'phase_name': phase_name,
            'phase_display': phase_display,
            'tags': ' '.join(post.get('tags', [])),  # Join tags for full-text search
            'summary': post.get('summary', ''),
            'date_context': post.get('date_context', ''),
        }
        documents.append(doc)

    return documents

def generate_search_index(documents):
    """
    Generate Lunr.js-compatible index structure.
    This is a simple document list that can be searched client-side.
    """
    return {
        'version': '1.0',
        'generated': __import__('datetime').datetime.now().isoformat(),
        'documents': documents,
    }

def write_search_index(index_data, output_file):
    """Write search index to JSON file"""
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w') as f:
        json.dump(index_data, f, indent=2)
    print(f"✓ Generated search index: {output_file}")
    print(f"  {len(index_data['documents'])} documents indexed")

def generate_search_js(output_file):
    """Generate client-side search JavaScript"""
    search_js = '''
/**
 * search.js — Client-side search implementation for Chappaqua Poison
 * Auto-generated by build_search_index.py
 */

(function() {
  'use strict';

  const SearchEngine = {
    index: [],

    init: async function() {
      try {
        const response = await fetch('./search_index.json');
        const data = await response.json();
        this.index = data.documents || [];
        this.attachListeners();
      } catch (error) {
        console.error('Failed to load search index:', error);
      }
    },

    search: function(query) {
      if (!query || query.length < 2) return [];

      const q = query.toLowerCase();
      const results = [];

      for (const doc of this.index) {
        let score = 0;

        // Title match (highest weight)
        if (doc.title.toLowerCase().includes(q)) {
          score += 30;
          // Exact title match
          if (doc.title.toLowerCase() === q) {
            score += 20;
          }
        }

        // Phase match
        if (doc.phase.toLowerCase().includes(q) || doc.phase_name.toLowerCase().includes(q)) {
          score += 10;
        }

        // Tags match
        if (doc.tags.toLowerCase().includes(q)) {
          score += 15;
        }

        // Summary match
        if (doc.summary.toLowerCase().includes(q)) {
          score += 5;
        }

        // Date context match
        if (doc.date_context.toLowerCase().includes(q)) {
          score += 10;
        }

        if (score > 0) {
          results.push({
            ...doc,
            score: score
          });
        }
      }

      // Sort by relevance score descending
      results.sort((a, b) => b.score - a.score);

      return results.slice(0, 20);  // Return top 20 results
    },

    attachListeners: function() {
      const searchInput = document.getElementById('search-input');
      const searchResults = document.getElementById('search-results');

      if (!searchInput || !searchResults) return;

      searchInput.addEventListener('input', (e) => {
        const query = e.target.value.trim();

        if (query.length < 2) {
          searchResults.classList.add('hidden');
          return;
        }

        const matches = this.search(query);

        if (matches.length === 0) {
          searchResults.innerHTML = '<div class="search-result-item">No results found</div>';
          searchResults.classList.remove('hidden');
          return;
        }

        searchResults.innerHTML = matches.map(doc => `
          <a href="./posts/$${doc.id}.html" class="search-result-item">
            <div class="search-result-title">${this.escapeHtml(doc.title)}</div>
            <div class="search-result-meta">
              <span class="search-result-phase">${doc.phase_display || ('Act ' + doc.phase)}</span>
              <span class="search-result-date">${this.escapeHtml(doc.date_context)}</span>
            </div>
          </a>
        `).join('');

        searchResults.classList.remove('hidden');
      });

      searchInput.addEventListener('blur', () => {
        setTimeout(() => searchResults.classList.add('hidden'), 200);
      });
    },

    escapeHtml: function(text) {
      const div = document.createElement('div');
      div.textContent = text;
      return div.innerHTML;
    }
  };

  // Initialize on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => SearchEngine.init());
  } else {
    SearchEngine.init();
  }

  // Export for testing
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = SearchEngine;
  }
})();
'''
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w') as f:
        f.write(search_js)
    print(f"✓ Generated search.js: {output_file}")

def main():
    # Paths
    project_root = Path(__file__).parent.parent
    posts_file = project_root / 'posts.json'
    tokens_file = project_root / 'tokens.json'
    output_dir = project_root / '_site'
    index_file = output_dir / 'search_index.json'
    search_js_file = output_dir / 'js' / 'search.js'

    # Load and process
    print("Loading posts.json...")
    posts = load_posts(posts_file)
    print(f"  {len(posts)} posts loaded")

    print("Loading tokens.json for phase names...")
    tokens = load_tokens(tokens_file)

    print("Building search documents...")
    documents = build_search_documents(posts, tokens)

    print("Generating search index...")
    index_data = generate_search_index(documents)

    # Write outputs
    write_search_index(index_data, str(index_file))
    generate_search_js(str(search_js_file))

    print("\n✓ Search index build complete!")
    return 0

if __name__ == '__main__':
    sys.exit(main())
