#!/usr/bin/env python3
"""
context_pass.py — Adds narrative context to all hero and primary evidence items.
Evidence without context is a brief. Evidence with context is a story.

⚠ DEPRECATED: This script's data has been absorbed into evidence_index_canonical.json.
To update evidence data, edit directly in canonical and re-run: python3 scripts/build_canonical_evidence_index.py
"""
import json

with open('v3_evidence_map_v2.json') as f:
    data = json.load(f)

# ─── HERO FIXES ──────────────────────────────────────────────────
HERO_FIXES = {

("B08", "D-7"): """Tara sent Steve a video of herself crying — mascara streaked, voice breaking — with a message saying she might be pregnant and didn't want to be. 'I don't want to be pregnant, and I can't even get myself to take a test. This is YOUR fault if I am.' But the video wasn't spontaneous. It had been rehearsed and sent to friends for feedback before Steve ever received it. A professional connected to the case later described it as 'one of the creepiest things I ever saw' — Tara alternating between a look of dark determination and full sobs, then back to the same dark scowl. The performance would become evidence not of distress but of calculation: a pregnancy announcement engineered for maximum emotional leverage.""",

("B09", "Hospital admission"): """In the summer of 2017, Tara handed Steve his Adderall bottle before he left her Brooklyn apartment for the night. At Ochoa's place, the pill produced not focused clarity but a widening strangeness — heat that shouldn't have been there, edges softening in ways amphetamines alone don't produce. By morning Steve was in an ER. What happened next was the trap: Tara appeared at the hospital, and the psychiatric commitment process began. A summary compiled for the legal team documents that Tara had admitted in sworn proceedings, declarations, and other communications to administering Seroquel — an antipsychotic — to Steve by slipping it into his drinks on multiple occasions without his knowledge or consent. The Brooklyn hospitalization wasn't a mental health crisis. It was the intended consequence of pharmaceutical tampering — and the template for discrediting everything he would later say.""",

("B11", "Crutcher Declaration"): """Bryan F. Crutcher — retired SFPD, head of BSecure — declared under oath on July 9, 2018 that he was retained to provide round-the-clock security for Steve, Tara, and baby Evie at the San Francisco residence. Crutcher had been watching the household with fifteen years of street experience, and what he saw alarmed him: Tara's erratic behavior, the nanny Abby Tedla's account of drugs being placed in Steve's drinks, and a domestic situation that required professional security intervention. His declaration corroborated Tedla's testimony — providing a second, independent witness to the drugging pattern. The significance was structural: this wasn't a he-said-she-said. It was a sworn, professional assessment by a man whose career had been spent distinguishing real threats from imagined ones.""",

("B12", "K-49"): """On the morning of January 27, 2018 — the day Evie was born by emergency C-section after Tara's blood pressure spiked — Tara arranged for Adderall to be delivered to Steve at the hospital. He had been sleeping in a recliner beside the bassinet for four days, and the delivery came wrapped in caretaking: here, take this, you need to stay awake. The chat.db message trail documents the coordination of the delivery. What it doesn't say — what Steve wouldn't understand until months later — is that the medication delivery to a hospital room, on the day of his daughter's birth, was consistent with the same pattern Tedla and Crutcher would later testify to: substances administered as care, timed for maximum vulnerability.""",

("B12", "K-50"): """A second set of chat.db messages from January 27, 2018 — Evie's birthday — documents that Tara received or had access to Ativan alongside the Adderall delivery. The multi-drug combination — an antipsychotic-class sedative with a stimulant — on the day a man's daughter is born by emergency surgery, while his partner manages his medications, captures the architecture of the poisoning in miniature: the timing calculated for when Steve was most dependent and least suspicious, the delivery disguised as care, the substances layered to produce effects that would be attributed to exhaustion and stress rather than drugging.""",

("B14", "K-37"): """Steve returned to the Brooklyn apartment on January 31, 2018 — four days after Evie's birth — and found the tamper screws moved from their eleven o'clock positions. The apartment had been entered while he sat in a hospital recliner watching his daughter breathe. Then came the fumes: sweet, chemical, industrial. An adhesive substance settled on his face, hardening over hours, taking three days to remove. The chat.db messages from this period document Steve texting Tara about what he was finding — the moved screws, the chemical smell — and her responses, which would later be understood as the responses of someone who already knew what he was discovering. When Walsh Sr. arrived and told Steve to leave, the trap was complete: describe what happened accurately and sound insane, or say nothing and lose access to your daughter.""",

("B15", "Audio recordings"): """Audio recordings from the October 2017 meeting at the Sheraton in San Francisco, where Steve met with Tara's family to discuss co-parenting. Steve's stated intention: 'It's important to have a meeting of the minds of how we are going to bring our daughter into the world and raise her.' Tara's focus, as captured on the recording, was exclusively financial — what Steve would provide, what the arrangements would cost, what she would receive. The audio documents the gap between what Steve believed the meeting was about (their daughter) and what Tara was actually negotiating (her financial position). The Sheraton meeting preceded the Adderall tampering at the hospital by three months.""",

("B16", "Text message exchanges"): """Between February and March 2018, Tara called Steve nightly from New York — the time zone gap turning his California afternoons into her evening monologues. The text messages document a three-phase pattern that repeated across weeks: first, she blamed her parents ('Walsh Sr. overreacted, Maura was worried'); second, she promised cooperation ('I'll bring Evie to California, we'll share time'); third, the financial inventory — casual questions about Ring, stock options, security costs, nested inside conversations about the baby. Then she asked for a private jet. Not business class. A charter. The messages are significant because they capture Tara running the same play in both directions — telling Steve her parents were the problem while telling her parents Steve was the problem — and because the financial probing preceded the flight that would become the custody battle's opening move.""",

("B20", "Video recording"): """While Tara was being caught by Abby Tedla putting pills in Steve's wine in May 2018, she recorded the episode in real time — capturing on her own phone the very incident that would later become the central evidence against her. The nanny would tell the court: 'I was not going to lie for her.' Tara's decision to record the drugging — either as insurance, as documentation for her own legal strategy, or out of the compulsion to control the narrative even while committing the act — became one of the case's most revealing artifacts. She was simultaneously poisoning Steve and building a record, the way she had rehearsed the crying pregnancy video and manufactured bruise photographs.""",

("B21", "Tedla Sworn Declaration"): """From the Sworn Declaration of Abrehet Tedla, filed July 9, 2018 (FPT-18-377425):

'Ms. Walsh had been putting drugs in his drinks without his knowledge and she had asked me to lie and tell social services that he was a bad dad/person. Once Ms. Walsh realized I was not going to lie for her or condone her mistreatment and drugging of Mr. Russell, she began to treat me with distain and ultimately fired me.'

'I saw her drug him on at least two occasions; however she told me and Dan Ochoa that she "did it all the time." This caused me to fear for Mr. Russell's safety and I saw the effects on those two occasions after he drank the tainted wine. It appeared to cause him to lose consciousness shortly after.'

Tedla had called her brother in the FBI before coming to Steve in the kitchen. Her brother's instruction was immediate: tell him. The nanny who had been hired to care for a baby instead became the witness who broke the case open — the person who saw the surface of the household and what lay beneath it, and chose the truth over her job.""",

("B22", "Text message"): """The message arrived on a Tuesday, while Evie was in the next room with Abby and the fog pressed against the Millennium Tower windows fifty-eight stories up. Tara wrote in torrents — about Steve, the apartment, the security team, money — and buried in the middle: 'You almost made me abandon our daughter.' Steve read it twice. The phrase landed the way most of Tara's dramatic phrases landed — as rhetoric, as performance, as the kind of language she used when she wanted emotions louder than the situation. But it wasn't rhetoric. Within weeks, Tara would get into an Uber with Evie and attempt to leave the state. The message was a preview: the word 'abandon' had been chosen because the act was already being planned. Steve filed it as noise. It was a warning.""",

("B23", "Audio recording from the Uber"): """Audio recording captured during Tara's unauthorized departure with Evie in June 2018. When Tara abandoned the arranged security transport and called an Uber, Bryan Crutcher got in the back seat and texted Steve: 'She's in a car. She has the baby. She's headed to the bus zone.' The recording captured Walsh Sr.'s voice on the phone — not orchestrating a kidnapping but sounding like a panicking father who had been told by Tara that Steve was dangerous, that Evie was in danger, that his daughter needed to come home. But a later-discovered email told a different story: Walsh Sr. writing that he was 'giving Tara permission to leave CA' — the word 'permission,' from a father to his thirty-year-old daughter, the tell that the family's control architecture extended across three thousand miles.""",

("B25", "Motion documenting supervisor"): """In court filings, Steve's attorneys documented that the court-appointed visit supervisor had disclosed a 'special relationship with the judge' — Judge Farquharson — raising questions about the independence of the supervision arrangement. Over sixteen supervised visits across six supervisors, every report documented Evie's joy at seeing her father, her developmental progress, the absence of concerning behavior. If the supervision was neutral, the reports would have been damning for Tara's position. The supervisor's admission about her judicial relationship suggested the visits were being monitored not by a neutral party but by someone connected to the court — and that the consistently positive reports were reaching a judge who might have reason not to act on them.""",

("B27", "Photographs of injuries"): """Photographs taken during supervised visits showing bruises and injuries on Evie's body — marks discovered by Steve and the visit supervisor, including deep pinch marks noted by AFC Jennifer Jackman in her own correspondence. The injuries appeared between visits, during periods when Evie was in her mother's exclusive custody in Chappaqua. The photographs were submitted to the court. No investigation was ordered. The system that had separated Evie from her father based on allegations documented Evie's injuries in her mother's care and responded with silence — the asymmetry at the heart of the case, where one parent's words were treated as evidence and the other parent's photographs were treated as noise.""",

("B28", "LaMelle documentation"): """On September 21, 2019, court-appointed supervisor Claudette LaMelle (ACSW, LMSW) arrived at the Walsh compound for the first supervised visit after five months of complete denial of access. She was permitted through the electronic iron gate, then told Walsh wasn't there. At the drop-off, an unknown male and Brendan Walsh — Tara's brother — confronted LaMelle in a manner she documented as intimidation. The supervisor report was filed; a Petition for Enforcement followed three days later. The significance: even the court's own appointed supervisor was subject to the Walsh family's gatekeeping. The iron gate, the unknown man, the brother's presence — the architecture of control extended not just to Steve but to anyone the court sent to verify what was happening inside the compound.""",

("B33", "Court calendar records"): """Court records document the procedural asymmetry that defined the case: Steve's single near-default — after receiving less than twelve hours' notice that his remote appearance was denied, forcing an overnight cross-country flight from Kelly's hospital bedside — produced a custody order that separated him from his daughter. Tara's two actual defaults — failing to appear for scheduled evidentiary hearings where Steve's legal team was prepared and waiting — produced nothing. No default orders. No custody modifications. The court simply rescheduled. The contrast was mathematical: one alleged default for the father meant total loss of custody. Two confirmed defaults for the mother meant a new hearing date.""",

("B34", "Four Discoveries"): """Four independent discoveries, spanning 2017 to 2020, each confirmed from a different angle that Tara Walsh had been systematically drugging Steve Russell:

1. LITHIUM (2017): Blood test showed levels six times normal — Steve had no lithium prescription. The test was ordered by his own doctor during the period when three physicians couldn't explain his symptoms.

2. BROOKLYN HOSPITAL (2017): Steve was committed to a psychiatric ward after taking Adderall from a bottle Tara had handled. The tamper screws on the pill bottles had been at eleven o'clock when he left. They were not at eleven o'clock when he returned.

3. TEDLA DISCLOSURE (2018): The nanny walked into the kitchen and said 'This will probably get me fired.' She told Steve that Tara had been putting drugs in his drinks. She had called her brother in the FBI first. Her brother said: tell him immediately.

4. THE RENO BOTTLE (2020): Laboratory analysis of wine from Steve's Reno home detected Mycophenolic Acid — an organ transplant drug — at 7× the upper limit of normal. Both Steve and Kelly became violently ill after drinking it. Kelly later suffered a miscarriage.

The significance is cumulative: each discovery was independent, each involved different substances, different witnesses, different laboratories. No single discovery could be dismissed as coincidence or paranoia. Taken together, they described a pattern of poisoning sustained over years.""",

("B35", "Schauer vacatur"): """Judge Michelle Schauer vacated the default order that Judge Horowitz had entered — finding procedural deficiencies in its issuance. The vacatur should have been the beginning of restoration: the wrongful default removed, Steve's custody rights reopened for a hearing on the merits. Instead, the Family Court treated it as a technicality. Schauer issued a 'mutual' temporary restraining order — equating Steve, the documented victim of years of drugging and assault, with Tara, the perpetrator confirmed by two independent witnesses and multiple laboratory reports. Then the court proceeded to an inquest where Steve's evidence was never heard. The vacatur was the system admitting its error. What followed was the system refusing to act on its own admission.""",

("B36", "Linda Russell's letter"): """Steve's mother, Linda Russell, submitted a letter and a formal Notice of Motion to Vacate or Narrow Prior Speech Restrictions, invoking constitutional protections against prior restraint. The motion targeted the speech orders that prohibited Steve from discussing the case — orders that had been issued without the constitutionally required findings. The motion sought to preserve strict protection for Evie's identity, medical records, and images while restoring Steve's right to speak about court processes and corruption allegations as an adult, to adults. Linda Russell's intervention was significant because it came from outside the direct custody dispute — a grandmother asking the court to recognize that silencing her son about what happened to him was not the same as protecting her granddaughter.""",

("B37", "Gag order text"): """The Family Court's speech order required Steve to 'erase, deactivate, and delete any existing blogs and likenesses' — language so sweeping it demanded the destruction of an entire digital archive. The order was issued on the basis of a default that the Appellate Division would later hold did not occur, and without the constitutional findings required for prior restraint on speech. The three words — erase, deactivate, delete — captured the court's approach to Steve's First Amendment rights: not a carefully tailored restriction protecting Evie's privacy, but a blanket demand to unmake the record. When the Appellate Division reviewed the order in 214 A.D.3d 890, it held the restriction was not 'tailored as precisely as possible to the exact needs of the case' — constitutional language for: this was censorship, not protection.""",

("B39", "Petrella threat"): """A journalist who had been covering the case was contacted by individuals connected to the Walsh family's legal network and told: 'You are putting yourself in harm's way.' The journalist ceased coverage. The threat was significant not because it succeeded — though it did — but because it revealed the Walsh family's strategy extended beyond the courtroom. The same family that had used court orders to silence Steve was using direct intimidation to silence the press. The journalist's decision to stop reporting removed an independent verification layer from the story — exactly the outcome the threat was designed to produce.""",

("B43", "214 A.D.3d 890"): """Matter of Walsh v. Russell, 214 A.D.3d 890 (2d Dep't 2023)

The Appellate Division, Second Department, ruled unanimously on March 22, 2023:

First, 'contrary to the contention of the mother and the AFC, the order appealed from was not entered upon the father's default.' Steve's attorney had appeared, made objections, and cross-examined witnesses. The default that had anchored years of custody orders was a legal fiction — an event the court had treated as fact that the appellate record showed never occurred.

Second, the court struck the blanket speech order requiring Steve to 'erase, deactivate, and delete any existing blogs and likenesses' as unconstitutionally overbroad — not 'tailored as precisely as possible to the exact needs of the case.'

The decision (Barros, J.P., Miller, Genovesi, Wan, JJ., concurring) removed the two pillars the Family Court had built on: the default and the gag order. But the orders that rested on those pillars remained in effect. The appellate court said the foundation was invalid. The lower court did not remove the building. Evie remained inside.""",

("B44", "San Francisco Superior Court"): """In February 2022, a San Francisco jury heard four days of testimony in Russell v. Walsh (CGC-18-570137). Twelve citizens — none of whom knew Steve, Tara, or anyone in either family — listened to the nanny's account of the drugging, saw the text messages, reviewed the medical records, watched Brienne Walsh's uncontested deposition testimony, and heard Tara's own admissions. They were the first neutral decision-makers to hear the full evidence. They deliberated over a long weekend and returned a verdict finding Tara Walsh liable for battery, fraud, intentional infliction of emotional distress, and domestic violence — with a finding of malice, eleven to one. The California civil court did what the New York family courts had not: examined the evidence and reached a conclusion.""",

("B46", "California Court of Appeal"): """The California First District Court of Appeal affirmed the jury verdict in its entirety — finding sufficient evidence to support every count and upholding the malice finding and the damages award. Tara's attorneys challenged the sufficiency of the evidence, the jury instructions, and the trial procedures. The appellate court rejected each argument. The affirmance meant that two independent sets of neutral decision-makers — a jury and an appellate panel — had examined the same evidence and reached the same conclusion: Tara Walsh drugged and abused Stephen Russell. One legal system had compensated. The other still had the child.""",

("B47", "The archive itself"): """The archive — physical and digital — constitutes meta-evidence: the fact that this record exists at all. A September 28, 2018 letter from Steve's attorney to the San Francisco District Attorney, Head Deputy Rani Singh, formally demanded prosecution under California law, citing Tara's sworn admissions to administering Seroquel without consent. The demand letter summarized the case file: the laboratory reports, the declarations, the medical records, the text messages. The DA's office did not prosecute. But the letter survives as evidence of what was documented and delivered to authorities — and of what authorities chose not to act on. The archive's physical weight — binders, hardbound volumes, transcripts, the StevieLovesEvie books — is itself an argument: this is not a claim. This is a record.""",
}

# ─── PRIMARY FIXES ──────────────────────────────────────────────
PRIMARY_FIXES = {

("B02", "SLE blog post"): """The StevieLovesEvie blog documented the first meeting between Steve and Tara on a boat party in New York — the 'Girl on the Boat' origin story that would become the opening chapter of the case narrative. The blog post, written before the poisoning was understood, captures how the relationship appeared from the outside: charming, cinematic, a chance encounter that felt like fate. Read with the knowledge of what followed, the post becomes an artifact of a specific kind of irony — the story of a man meeting the person who would spend the next decade destroying him, told in the voice of someone who still thought it was a love story.""",

("B05", "Photographs of forced electrical"): """Photographs documenting the forced entry to the electrical closet at Steve's residence on Vermont Street. The closet door had been opened not by breaking the hinges but by removing the pins — a method requiring tools, patience, and the knowledge that this was how you gained access without leaving obvious damage. Several breaker switches had been flipped. The electrical access was significant because it preceded the drill holes: whoever entered Steve's home first disabled the power distribution system, then systematically drilled through walls, baseboards, and floors. Nothing was stolen. The television was on the wall, the laptop on the desk. The only evidence of entry was structural — suggesting the purpose was not theft but surveillance installation or environmental tampering.""",

("B05", "Photos of drill holes"): """Interior photographs showing drill holes throughout Steve's residence — small, round, clean, evenly spaced along hallways, bedroom walls, baseboards, and the floor. The pattern was not random: the holes were the work of someone who knew exactly what they were looking for within the walls, or someone installing access points for a purpose Steve wouldn't understand until the Brooklyn apartment fumes three years later. Steve photographed every hole, every moved breaker, every extracted hinge pin. The documentation reflex — the same instinct that had him setting tamper screws to eleven o'clock — would later provide the physical evidence trail that connected the Vermont Street break-in to the broader pattern of environmental tampering.""",

("B05", "Security camera records"): """Security camera footage from the Vermont Street residence capturing the timeline of the break-in. The cameras — part of the Ring system Steve had helped design — recorded the exterior activity surrounding the forced entry to the electrical closet. The footage established that the intrusion was not opportunistic but planned: the timing, the method of entry, the systematic approach to the power system all indicated advance knowledge of the property's layout. The irony was structural: the man who had built video security technology for millions of homes had his own home breached by someone sophisticated enough to disable the system first.""",

("B06", "Medical records — conflicting"): """Medical records from 2016-2017 documenting the parade of conflicting diagnoses Steve received as his health deteriorated. Three doctors couldn't explain what was happening — the symptoms didn't fit any single condition. He was tested for Lyme disease, for autoimmune disorders, for neurological conditions. Each test returned inconclusive or contradictory results. The medical records are significant not for what they found but for what they couldn't find: no doctor considered poisoning because no doctor was looking for it. The gap between Steve's symptoms and any legitimate diagnosis was itself evidence — the medical system's inability to explain what Seroquel, Lithium, and Mycophenolic Acid were doing to a body that had no prescriptions for any of them.""",

("B07", "chat.db messages — breakup"): """The chat.db message archive from the breakup period captures the private communications between Steve and Tara in the weeks surrounding the wine bottle incident — the night Tara threw a full Pinot Noir at Steve's head and, when he reached for his phone, said: 'If you call the police, I'll tell them you hit me.' The messages document Tara's tone shifting between contrition, accusation, and financial negotiation — the same three-phase pattern that would repeat years later during the custody dispute. The deal Steve made that night — 'I won't call. You leave.' — set the precedent: he chose resolution over documentation, protecting his future self's ability to act over his present self's right to a police report. It was the first time the trap was visible: report what happened and face her counterclaim, or stay silent and lose the record.""",

("B08", "Doctor's note confirming"): """OB-GYN documentation confirming Tara's pregnancy — the medical record that transformed an abstract claim into a concrete reality. Steve had received Tara's rehearsed crying video, her dramatic texts about possibly being pregnant. The doctor's note was the first piece of clinical evidence: yes, she was pregnant. The note became the anchor that kept Steve tethered to a relationship he had been trying to leave since the wine bottle incident. Without the pregnancy, he would have been gone — restraining order filed, apartment secured, the full distance of a continent between them. The doctor's note was the document that made Evie real and made leaving impossible.""",

("B08", "Author account — pregnancy claims"): """Tara's pregnancy claims followed a pattern Steve wouldn't recognize until later. There had been prior claims — references to possible pregnancies that produced urgent emotional responses and then resolved without explanation. The pattern was: create a crisis that requires Steve's presence, generate emotional dependency through the crisis, then let the crisis dissolve once the attachment has been reinforced. The actual pregnancy with Evie was real, but it arrived within a sequence of prior claims that had trained Steve to respond with protective urgency to any mention of pregnancy. By the time the OB-GYN confirmed the pregnancy was real, the response pattern was already established: Steve would do anything to protect his child, including remain in proximity to the person poisoning him.""",

("B09", "Messages — Tara's reaction"): """Text messages from Tara following the failed psychiatric commitment attempt — the night Steve ended up in a Brooklyn ER after taking Adderall from a bottle she had handled. Tara's messages in the aftermath were not those of a concerned partner. They were the messages of someone managing a situation that had not produced the intended outcome. The commitment was supposed to stick — Steve was supposed to be held, diagnosed, documented as mentally ill, and the custody path would have been clear. When he was released instead, Tara's texts shifted: from concern to frustration to the rapid recalibration of a person adjusting to a plan that didn't work. The messages are significant because they capture the emotional architecture of someone whose distress is strategic rather than genuine.""",

("B10", "EXHIBIT_P2"): """Email chain, March–August 2018, documenting the Amazon transmittal standoff. After Amazon acquired Ring for over $1 billion, the transmittal documents required Steve to sign a general release of all claims to receive any acquisition proceeds. Steve's advisors requested a carve-out — a way to preserve his claims while accepting the payout. Ring's outside counsel Roxana Azizi responded that the transmittal 'cannot be modified' and that even if it could, Ring was 'not willing to carve out or exclude any claims.' The ultimatum was explicit: sign everything and release all claims, or receive nothing. The transmittal standoff was significant because it demonstrated how Ring's corporate machinery — controlled by Jamie Siminoff, who had personally netted roughly $300 million — was being used to eliminate Steve's legal leverage at the exact moment when Steve most needed financial resources to fight for custody of his daughter.""",

("B10", "Prism Skylabs Mail — Termination"): """Email dated April 27, 2017, from Steve to Jamie Siminoff, Faisal Rashid at Fenwick & West, and Ring's general counsel Leila Rouhi, containing the termination agreement for the Prism-Ring licensing arrangement. Steve had designed the terms as a strategic instrument: Ring could cancel the deal, but had to return all of Prism's intellectual property. Jamie signed it — possibly without understanding that the entire Ring Pro architecture was Prism Vision, that the Ukraine team had been built on Prism's network, that the Series B fundraising deck had been written by Prism engineers. The termination agreement became the legal instrument that documented everything Jamie would later deny: that Ring's core technology belonged to someone else.""",

("B11", "K-82"): """Chat.db messages from December 21, 2017 — a thread involving Linda Russell (Steve's mother) — in which the subject of Evie's birth certificate was discussed. The messages documented that Steve's name on the birth certificate was being treated as a bargaining chip rather than a right. The leverage was implicit: cooperate with Tara's terms or risk being excluded from your daughter's legal identity. The birth certificate gambit was significant because it preceded Evie's birth by five weeks — evidence that the custody architecture was being constructed before the child was born, while Steve was still setting tamper screws and scheduling hospital logistics and believing he was preparing for a family.""",

("B12", "Hospital records — emergency"): """Medical records from Columbia Presbyterian documenting Evie's emergency C-section on January 27, 2018. Tara's preeclampsia had escalated — blood pressure readings that had been 'concerning' became critical, and the specialist Steve had arranged months earlier performed the emergency delivery. The hospital records establish the clinical context for everything that happened in the following days: the Adderall delivery to the hospital room, the multi-drug exposure documented in the chat.db messages, the four days Steve spent in a recliner beside the bassinet while the Walsh family filled the corridors. The birth was both the beginning of Evie's life and the beginning of the custody war — the moment when the stakes became a person rather than a legal argument.""",

("B14", "Crutcher Declaration"): """Bryan Crutcher's July 2018 declaration addressed the January 2018 events at the Brooklyn apartment — the period surrounding Evie's birth when Steve was sleeping in a hospital recliner and the apartment was being entered in his absence. Crutcher's declaration corroborated the tamper screw evidence and the security team's assessment that the apartment had been compromised. The declaration was significant because Crutcher had been present in New York during this period — he had flown with Steve from SFO, arranged the NYPD drivers, and observed the Walsh family's movements around the hospital. His testimony provided a professional security assessment of what Steve described: not paranoia but a documented pattern of intrusion consistent with the broader poisoning campaign.""",

("B15", "Author account — Ackerman"): """At a rest stop between San Francisco and Reno, Steve met with Don Ackerman — the security consultant who had been billing Steve tens of thousands a month. Ackerman arrived with an evidence box, which he handed to Steve. The box contained materials that Ackerman said were relevant to Steve's safety situation. What Steve did not yet know — what the Enenstein correspondence would later reveal — was that Ackerman's security operation had been coordinating with the Walsh family throughout this period. The man hired to protect Steve was communicating with the people Steve needed protection from. The rest stop handoff was the architecture of Legacy Protection made physical: the illusion of security covering the reality of surveillance.""",

("B16", "Phone records"): """Phone records from February–March 2018 documenting the volume and pattern of calls between Tara in New York and Steve in San Francisco. The records establish the frequency and duration of Tara's nightly calls — data that corroborates Steve's account of the negotiation pattern (blame parents → promise cooperation → financial probing → escalating demands). The call records also document the week leading up to the charter jet booking — the acceleration in call frequency as Tara moved from asking about Steve's finances to requesting a private plane. The phone records provide the quantitative skeleton beneath the qualitative account: not just what was said, but how often, how long, and when the pattern shifted.""",

("B18", "Tedla Sworn Declaration"): """Tedla's July 9, 2018 declaration (FPT-18-377425) provided the primary appendix material supporting her hero testimony about the drugging. The full declaration detailed not only the two occasions Tedla personally witnessed Tara drugging Steve's wine, but the household dynamics that surrounded the drugging: Tara's request that Tedla lie to social services, Tara's treatment of Tedla deteriorating once the nanny refused to participate in the deception, and Tedla's ultimate firing — not for poor performance but for refusing to be complicit. The declaration established Tedla as a reluctant witness: someone who didn't seek out this information but couldn't unsee it, and whose professional and personal costs for telling the truth were immediate and real.""",

("B21", "Crutcher Sworn Declaration"): """Bryan Crutcher's July 9, 2018 declaration (FPT-18-377425) was filed alongside Tedla's declaration as companion testimony. Where Tedla described what she saw inside the household — the drugging, the lies, the firing — Crutcher described what he saw from the security perimeter: the behavioral patterns, the threat assessment, the professional judgment of a retired SFPD officer who had spent fifteen years reading dangerous situations. Crutcher's declaration corroborated Tedla from a different angle and with different professional authority. Together, the two declarations created a cross-referenced account: the nanny and the security chief, each witnessing the same pattern from different vantage points, each swearing to it independently.""",

("B23", "Emergency court filings"): """Stacey Poole filed emergency motions within hours of Tara's unauthorized departure with Evie in the Uber. The filings described the departure, the circumvention of arranged security transport, the attempt to leave the city with the child — and requested emergency custody relief. The court responded the same day: Evie was blocked from leaving California, Steve received emergency custody, and Tara was limited to supervised visitation. The emergency filings were significant because they produced the first formal court acknowledgment that Steve's custody of his daughter was the safer arrangement — a finding that the New York courts, operating with Tara's version of events, would spend years attempting to reverse.""",

("B23", "Crutcher Declaration"): """Crutcher's declaration as it pertained to the Uber incident documented the security team's real-time response: the observation that Tara had abandoned arranged transport, the decision to follow, Bryan physically entering the Uber to maintain contact with the baby. Crutcher's training — fifteen years SFPD — was visible in his actions: he didn't confront Tara, didn't create a scene, simply got in the car and began texting Steve factual updates. The declaration established that the departure was not spontaneous but anticipated: the security team had been watching Tara's behavior patterns and recognized the signs of an exit before it happened.""",

("B25", "Court order governing"): """The court order establishing the terms of supervised visitation documented the specific conditions under which Steve was permitted to see his daughter — conditions that, taken together, revealed a system designed to minimize rather than facilitate contact. Visit locations were specified and controlled. Supervisors were appointed by the court. Timing was restricted. The order created a framework where every interaction between a father and his daughter was mediated, observed, and documented — while the mother's unsupervised custody in Chappaqua went unmonitored. The order's significance was what it did not contain: any provision for escalating to unsupervised contact, any mechanism for reviewing the arrangement's necessity, any acknowledgment that sixteen consecutive positive supervision reports might warrant a change.""",

("B25", "Supervisor billing records"): """Billing records from the court-appointed visit supervisors documented the financial cost of the supervised visitation regime — costs borne entirely by Steve. Each supervised hour required a professional supervisor's time, travel, and reporting. The cumulative billing established that maintaining contact with his daughter had become a line item on a financial statement — and that the arrangement had no built-in mechanism for termination. The billing records were significant because they revealed the economic architecture of the custody system: the more Steve fought to see his daughter, the more it cost, and the more he paid, the more the system treated the payment itself as evidence that the arrangement should continue.""",

("B26", "Supervisor reports"): """Over the course of sixteen supervised visits across six different supervisors, every report documented the same pattern: Evie's joy at seeing her father, her developmental progress during visits, the complete absence of concerning behavior. The reports described a child who was happy, engaged, and comfortable with Steve — and a father who was attentive, appropriate, and responsive. Multiple reports later disappeared from the court file without explanation or docket entry. The supervisor reports were the system's own evidence contradicting the system's own conclusions: the court had ordered supervision to protect Evie from her father, and the supervision itself documented that Evie didn't need protection from her father.""",

("B29", "Gordon-Oliver recusal"): """Judge Arlene Gordon-Oliver recused herself from the case — the first in what would become a pattern of judicial departures. The recusal order did not explain the reason, as recusal orders rarely do. What the record showed was that Gordon-Oliver had presided over the initial UCCJEA petition, had been present for the earliest phase of the custody dispute, and had then removed herself from a case she had been handling. The recusal was significant because it was followed by Humphreys' recusal and Jackman's resignation — a pattern of institutional departure that suggested each successive decision-maker, upon seeing the full picture, chose to leave rather than act on what they saw.""",

("B31", "ExI_02"): """LabCorp Heavy Metals Toxicology Report, January 2020, documenting the laboratory analysis of wine from Steve's Reno residence — the bottle that had traveled from San Francisco and been preserved for testing. The report identified Mycophenolic Acid at 349.87 nanograms per gram creatinine, against a reference range of 5 to 50 — seven times the upper limit of normal. Mycophenolic Acid is an immunosuppressant (brand name CellCept) prescribed exclusively to organ transplant recipients. Neither Steve nor Kelly had a transplant or a prescription. The wine was the same bottle from the night both Steve and Kelly became violently ill — Kelly's illness leading to emergency surgery and a miscarriage. The lab report transformed a domestic poisoning allegation into a quantified, scientifically documented fact.""",

("B32", "Court notice denying"): """The court notice denying Steve's request for remote appearance arrived at 5:00 PM the evening before the hearing — a timing that appeared calculated to make compliance as difficult as possible. Steve was in Nevada, where Kelly was recovering from surgery. Cross-country flights at that hour are scarce. Overnight options require airport transit during hours when connections are limited. The notice gave Steve less than twelve hours to leave Kelly's hospital bedside, drive to an airport, book and board a redeye, fly through the night, land in New York, and arrive at a courthouse in Yonkers. The timing wasn't a scheduling coincidence. It was the mechanism by which his absence would be manufactured and then recorded as default.""",

("B34", "ExA_02"): """Laboratory analysis identifying Mycophenolic Acid in the Reno wine sample at 349.87 ng/g creatinine — seven times the upper limit of normal. This was Discovery 4, the most dramatic quantitative evidence in the case. Mycophenolic Acid is an immunosuppressant prescribed exclusively to organ transplant recipients. Steve had no transplant. Kelly had no transplant. Neither had a prescription. The wine had traveled from the Potrero Hill apartment in San Francisco to Reno, where both Steve and Kelly drank from it. Both became violently ill. Kelly required emergency surgery and suffered a miscarriage. The lab report did what the medical records from 2016-2017 couldn't: it identified a specific substance, at a specific concentration, in a specific vessel, producing specific harm to specific victims. The circumstantial had become chemical.""",

("B35", "Mutual temporary restraining"): """After vacating the Horowitz default, Judge Schauer issued a 'mutual' temporary restraining order — applying identical restrictions to both Steve and Tara. The legal equivalence was factually false: Steve had been documented as the victim of years of drugging by two independent witnesses, multiple laboratory reports, and sworn declarations. Tara had been found liable for battery, fraud, and domestic violence by a jury. The mutual TRO treated the perpetrator and the victim as symmetrical threats — the legal equivalent of responding to a documented assault by restraining both the assailant and the person who was assaulted. The order established the pattern that would define the post-vacatur proceedings: the Family Court absorbing its own errors by distributing the consequences equally, regardless of the evidence.""",

("B36", "StevieLovesEvie.com blog"): """Kelly Turnure published Linda Russell's letter to the court on the StevieLovesEvie.com website — making public a grandmother's plea that had been filed in a sealed family court proceeding. The publication was an act of deliberate transparency: if the court would not act on the letter, the public would at least be able to read it. Kelly's decision to publish reflected the same logic that would inform the entire blog archive — that the sealed proceedings, the gag orders, the speech restrictions were protecting not Evie's privacy but the system's accountability gap. The blog post included Linda's letter alongside context establishing why a grandmother was writing to a court asking for the right to see her granddaughter.""",

("B39", "B39_custody_order"): """A photograph of a court order that was circulated outside confidential Family Court proceedings — evidence that sealed court documents were being shared by the Walsh side to third parties while Steve was simultaneously being gagged from discussing the case publicly. The asymmetry was telling: the same family that had sought and obtained speech restrictions against Steve was itself distributing court orders to people outside the case. The circulation of the custody order demonstrated that the gag order's purpose was not protecting Evie's privacy — it was ensuring that only one side's narrative reached the public.""",

("B44", "Trial transcript"): """The trial transcript from Russell v. Walsh (CGC-18-570137) in San Francisco Superior Court documented four days of testimony heard by twelve jurors. The transcript captured Abby Tedla's testimony — the nanny describing what she saw in the kitchen, what Tara asked her to do, what happened when she refused. It captured the introduction of text messages showing the gap between Tara's private communications and her public representations. It captured the admission of Brienne Walsh's deposition without objection — Tara's own counsel declining to challenge her sister's testimony about childhood abuse, CPS calls, and the phrase 'We were hit.' The transcript was the first complete evidentiary record assembled in any courtroom: everything the Family Court had refused to hear, heard in full.""",

("B48", "CustodyPetitionMotion"): """The Custody Petition Motion with Exhibits, specifically page 77, documented the Russell-Walsh correspondence surrounding Tara's post-verdict demand: drop the judgment, show the Walsh family 'respect,' and only then would Steve be permitted to see his daughter. The filing preserved the demand in the court record — ensuring that Tara's conditions for allowing father-daughter contact were documented under penalty of perjury. The correspondence revealed that even after a jury verdict, an appellate affirmance, and years of documented poisoning, the Walsh family's position remained unchanged: access to Evie was conditional on Steve's silence about what they did to him.""",

("B48", "ExCC_01 Master Timeline"): """The Master Timeline entry documenting Tara's demand — compiled as part of the comprehensive case chronology — placed the demand within the broader sequence of events: after the jury verdict (2022), after the appellate affirmance (2023), after the Appellate Division reversed the default and gag order (2023). The timeline entry established that Tara's demand was not a negotiating position but an ultimatum: the verdict, the record, the evidence — all of it had to disappear before Evie could see her father. The demand was the final piece of the pattern: courts had confirmed the poisoning, juries had confirmed the abuse, but the child remained in the custody of the confirmed abuser because the Family Court had not yet acted on any of it.""",
}

# ─── APPLY FIXES ──────────────────────────────────────────────

hero_fixed = 0
for (pid, prefix), text in HERO_FIXES.items():
    found = False
    for item in data[pid].get('hero', []):
        if prefix.lower() in item['exhibit_name'].lower():
            item['embed_text'] = text.strip()
            found = True
            hero_fixed += 1
            break
    if not found:
        print(f"MISS hero {pid}: {prefix}")

pri_fixed = 0
for (pid, prefix), text in PRIMARY_FIXES.items():
    found = False
    for item in data[pid].get('primary', []):
        if prefix.lower() in item['exhibit_name'].lower():
            item['appendix_text'] = text.strip()
            found = True
            pri_fixed += 1
            break
    if not found:
        print(f"MISS primary {pid}: {prefix}")

with open('v3_evidence_map_v2.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"\nHero items fixed: {hero_fixed}")
print(f"Primary items fixed: {pri_fixed}")
print(f"Total: {hero_fixed + pri_fixed}")
